# A simple action usage
name: Build Kernel
on:
  workflow_dispatch:

jobs:
  Build-Kernel:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Build Kernel
        uses: dabao1955/kernel_build_action@main
        with:
          kernel-url: https://github.com/ygorigor/android_kernel_realme_nemo
          kernel-dir: nemo
          kernel-branch: lineage-23.0
          config: nemo_defconfig
          arch: arm64
          aosp-gcc: false
          aosp-clang: false
          other-gcc32-url: https://github.com/LineageOS/android_prebuilts_gcc_linux-x86_arm_arm-linux-androideabi-4.9
          other-gcc32-branch: lineage-19.1
          other-gcc64-url: https://github.com/LineageOS/android_prebuilts_gcc_linux-x86_aarch64_aarch64-linux-android-4.9
          other-gcc64-branch: lineage-19.1
          other-clang-url: https://github.com/LineageOS/android_prebuilts_clang_kernel_linux-x86_clang-r416183b
          other-clang-branch: lineage-20.0
          ksu: false
          ksu-version: main
         # android-version: false
          aosp-clang-version: r522817
          disable-lto: false
          anykernel3: true
